import React from 'react';
import { Document, Page, Text, View, StyleSheet, Image, Font } from '@react-pdf/renderer';

// Register Nunito Sans using Direct TTF URLs from Fontsource CDN to fix "Unknown font format" bug
Font.register({
  family: 'Nunito Sans',
  fonts: [
    { src: 'https://cdn.jsdelivr.net/fontsource/fonts/nunito-sans@latest/latin-400-normal.ttf', fontWeight: 400 },
    { src: 'https://cdn.jsdelivr.net/fontsource/fonts/nunito-sans@latest/latin-600-normal.ttf', fontWeight: 600 }
  ]
});

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
    fontFamily: 'Nunito Sans',
  },
  header: {
    marginBottom: 30,
    borderBottom: 2,
    borderBottomColor: '#ffa724',
    paddingBottom: 10,
  },
  title: {
    fontSize: 22,
    fontWeight: 600,
    color: '#095546', // Dark Turquoise
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  subtitle: {
    fontSize: 11,
    color: '#ffa724', // Aksana Orange
    marginTop: 5,
    fontWeight: 600,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 9,
    fontWeight: 600,
    color: '#095546',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 10,
    backgroundColor: '#f0f9f8', // Very light turquoise tint
    padding: 6,
    borderRadius: 4,
  },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#f0f9f8',
    paddingVertical: 8,
    alignItems: 'center',
  },
  label: {
    fontSize: 9,
    color: '#475569',
    flex: 1,
  },
  value: {
    fontSize: 9,
    fontWeight: 600,
    color: '#095546',
    width: 100,
    textAlign: 'right',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 7,
    color: '#94A3B8',
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#f0f9f8',
    paddingTop: 10,
  }
});

const MeetingPDFReport = ({ data, chartImages }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>Aksana Executive Report</Text>
        <Text style={styles.subtitle}>Weekly Review: {data.date}</Text>
      </View>

      {/* KPI Summary */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Strategic Performance Overview</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Good News (Business)</Text>
          <Text style={[styles.value, { width: 'auto', flex: 2, textAlign: 'left', marginLeft: 20 }]}>{data.goodNewsBusiness}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Good News (Personal)</Text>
          <Text style={[styles.value, { width: 'auto', flex: 2, textAlign: 'left', marginLeft: 20 }]}>{data.goodNewsPersonal}</Text>
        </View>
      </View>

      {/* Attendance */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Attendance Ledger</Text>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10 }}>
          {data.attendance.map((att, i) => (
            <Text key={i} style={{ fontSize: 9, color: att.present ? '#10B981' : '#EF4444' }}>
              • {att.role} {att.present ? '(Present)' : '(Absent)'}
            </Text>
          ))}
        </View>
      </View>

      {/* IDT Issues */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Session IDT (Issues, Discussion, Tasks)</Text>
        {data.idtIssues.map((issue, i) => (
          <View key={i} style={styles.row}>
            <Text style={styles.label}>{issue}</Text>
          </View>
        ))}
      </View>

      {/* Charts if available */}
      {chartImages?.waterfall && (
        <View style={styles.chartContainer}>
          <Text style={styles.sectionTitle}>Impact Analysis Visualization</Text>
          <Image src={chartImages.waterfall} style={styles.chart} />
        </View>
      )}

      {/* Footer */}
      <Text style={styles.footer}>
        generated by Aksana Business Intelligence Engine
      </Text>
    </Page>
  </Document>
);

export default MeetingPDFReport;
